sudo: required
os:
  - linux

matrix:
	include:
		- language: bash
		services:
		  - docker
		before_script:
		  - docker pull node:slim
		script:
		  - bash jenkins.bash
		
		- language: python
		python:
		  - 2.7
		  - 3.3
		  - 3.4
		  - 3.5
		  - 3.6
		os:
		  - linux
		install:
		  - pip install tox-travis
		script: tox

notifications:
		  email: false